//----------------------------------------------------//
// MWT C++ Application Source File                    //
//      created by WideStudio Application Builder     //
//----------------------------------------------------//
#include <WScom.h>
#include <WSDappDev.h>

//--- OBJECT includes ---//
#include <WSCmainWindow.h>
#include <WSCform.h>
#include <WSCopenglForm.h>
#include <WSCvbtn.h>
#include <WSClist.h>
#include <WSCtextField.h>
#include <WSCvlabel.h>
#include <WSCvline.h>
#include <WSCdialog.h>
#include <WSCtform.h>
#include <WSCvifield.h>
#include <WSCradioGroup.h>
#include <WSCvradio.h>

//--- OBJECT instance variable ---//
WSCmainWindow* Kodatuno_Win = NULL;
WSCform* Graphic_Form = NULL;
WSCopenglForm* Describe_Form = NULL;
WSCform* Menu_Form = NULL;
WSCvbtn* Open_Body_Btn = NULL;
WSCvbtn* User_Func_Btn5 = NULL;
WSCvbtn* User_Func_Btn4 = NULL;
WSCvbtn* User_Func_Btn3 = NULL;
WSCvbtn* User_Func_Btn2 = NULL;
WSCvbtn* User_Func_Btn1 = NULL;
WSCvbtn* Del_Body_Btn = NULL;
WSClist* Body_List_Win = NULL;
WSCvbtn* User_Stat_Btn = NULL;
WSCtextField* Console_Form = NULL;
WSCvlabel* Label_1 = NULL;
WSCvline* Line = NULL;
WSCform* View_Form = NULL;
WSCvbtn* ViewOnX = NULL;
WSCvbtn* ViewOnY = NULL;
WSCvbtn* ViewOnZ = NULL;
WSCvbtn* ViewOnXYZ = NULL;
WSCvbtn* ViewSolid = NULL;
WSCvbtn* ViewWireFrame = NULL;
WSCvbtn* ViewFit = NULL;
WSCvbtn* ViewVoid = NULL;
WSCvbtn* SelectCancel = NULL;
WSCvbtn* ViewErase = NULL;
WSCvbtn* ViewBlend = NULL;
WSCvbtn* SelectAll = NULL;
WSCvbtn* ViewNoEdge = NULL;
WSCdialog* RotSurf_Dlg = NULL;
WSCtform* AxisOfRotation_Form = NULL;
WSCvlabel* AOR_Label_X = NULL;
WSCvlabel* AOR_Label_Y = NULL;
WSCvlabel* AOR_Label_Z = NULL;
WSCvifield* AOR_X = NULL;
WSCvifield* AOR_Y = NULL;
WSCvifield* AOR_Z = NULL;
WSCtform* RotAng_Form = NULL;
WSCvifield* AOR_Ang = NULL;
WSCdialog* NurbsCurve_Dlg = NULL;
WSCradioGroup* NurbsCOpt = NULL;
WSCvbtn* OpenInpFile_Btn = NULL;
WSCvifield* InpFileName = NULL;
WSCvlabel* NurbsC_Rank_Lb = NULL;
WSCvifield* NurbsC_Rank = NULL;
WSCdialog* User_Stat_Dlg = NULL;
WSCvlabel* Uer_Prop1_Lab = NULL;
WSCvlabel* User_Prop2_Lab = NULL;
WSCvifield* User_Prop1 = NULL;
WSCvifield* User_Prop2 = NULL;
WSCvlabel* User_Prop3_Lab = NULL;
WSCvlabel* User_Prop4_Lab = NULL;
WSCvlabel* User_Prop5_Lab = NULL;
WSCvifield* User_Prop3 = NULL;
WSCvifield* User_Prop4 = NULL;
WSCvifield* User_Prop5 = NULL;
WSCvlabel* Uer_Prop7_Lab = NULL;
WSCvlabel* Uer_Prop8_Lab = NULL;
WSCvlabel* Uer_Prop9_Lab = NULL;
WSCvlabel* Uer_Prop10_Lab = NULL;
WSCvifield* User_Prop6 = NULL;
WSCvifield* User_Prop7 = NULL;
WSCvifield* User_Prop8 = NULL;
WSCvifield* User_Prop9 = NULL;
WSCvifield* User_Prop10 = NULL;
WSCtform* UerMode = NULL;
WSCvradio* UserMode1 = NULL;
WSCvradio* UserMode2 = NULL;
WSCvradio* UserMode3 = NULL;
WSCvradio* UserMode4 = NULL;
WSCvradio* UserMode5 = NULL;
WSCvradio* UserMode6 = NULL;
WSCvradio* UserMode11 = NULL;
WSCvradio* UserMode7 = NULL;
WSCvradio* UserMode8 = NULL;
WSCvradio* UserMode9 = NULL;
WSCvradio* UserMode10 = NULL;
WSCvradio* UserMode12 = NULL;
WSCvradio* UserMode13 = NULL;
WSCvradio* UserMode14 = NULL;
WSCvradio* UserMode15 = NULL;
WSCvlabel* Uer_Prop11_Lab = NULL;
WSCvlabel* Uer_Prop6_Lab = NULL;
WSCvifield* User_Prop11 = NULL;
WSCvlabel* Uer_Prop12_Lab = NULL;
WSCvlabel* Uer_Prop13_Lab = NULL;
WSCvlabel* Uer_Prop14_Lab = NULL;
WSCvlabel* Uer_Prop15_Lab = NULL;
WSCvifield* User_Prop12 = NULL;
WSCvifield* User_Prop13 = NULL;
WSCvifield* User_Prop14 = NULL;
WSCvifield* User_Prop15 = NULL;
WSCdialog* SweepSurf_Dlg = NULL;
WSCtform* DirectionOfSweep_Form = NULL;
WSCvlabel* DOS_Label_X = NULL;
WSCvlabel* DOS_Label_Y = NULL;
WSCvlabel* DOS_Label_Z = NULL;
WSCvifield* DOS_X = NULL;
WSCvifield* DOS_Y = NULL;
WSCvifield* DOS_Z = NULL;
WSCtform* SweepLen_Form = NULL;
WSCvifield* Sweep_Length = NULL;
WSCdialog* NurbsSurface_Dlg = NULL;
WSCradioGroup* NurbsSOpt = NULL;
WSCvbtn* OpenNurbsSInpFile_Btn = NULL;
WSCvlabel* NurbsS_Rank_Lb = NULL;
WSCvifield* NurbsS_Rank = NULL;

//--- OBJECT src ---//

WSCbase* _create_win_Kodatuno_Win(){


  Kodatuno_Win = new  WSCmainWindow(NULL,"Kodatuno_Win");
      Kodatuno_Win->initialize();
  Kodatuno_Win->setPropertyV(WSNname,"Kodatuno_Win");
  Kodatuno_Win->setPropertyV(WSNtitleString,"Kodatuno");
  Kodatuno_Win->setPropertyV(WSNx,(short)100);
  Kodatuno_Win->setPropertyV(WSNy,(short)100);
  Kodatuno_Win->setPropertyV(WSNwidth,(unsigned short)830);
  Kodatuno_Win->setPropertyV(WSNheight,(unsigned short)660);
  Kodatuno_Win->setPropertyV(WSNbackColor,"#a0a0a0");
  Kodatuno_Win->setPropertyV(WSNtopShadowColor,"DEF15");
  Kodatuno_Win->setPropertyV(WSNbottomShadowColor,"DEF16");
  Kodatuno_Win->setPropertyV(WSNvis,(WSCbool)1);
  Kodatuno_Win->setPropertyV(WSNpixmapStyle,(unsigned char)1);
    extern void Kodatuno_Win_Proc(WSCbase*);
    Kodatuno_Win->addProcedureV("Kodatuno_Win_Proc","Kodatuno_Win_Proc",Kodatuno_Win_Proc,0);
    extern void Kodatuno_Win_Proc(WSCbase*);
    Kodatuno_Win->addProcedureV("Kodatuno_Win_Proc","Kodatuno_Win_Proc",Kodatuno_Win_Proc,32);
    extern void Kodatuno_Win_Proc(WSCbase*);
    Kodatuno_Win->addProcedureV("Kodatuno_Win_Proc","Kodatuno_Win_Proc",Kodatuno_Win_Proc,10);

  Graphic_Form = new  WSCform(Kodatuno_Win,"Graphic_Form");
      Graphic_Form->initialize();
  Graphic_Form->setPropertyV(WSNname,"Graphic_Form");
  Graphic_Form->setPropertyV(WSNx,(short)50);
  Graphic_Form->setPropertyV(WSNy,(short)5);
  Graphic_Form->setPropertyV(WSNwidth,(unsigned short)640);
  Graphic_Form->setPropertyV(WSNheight,(unsigned short)480);
  Graphic_Form->setPropertyV(WSNshadowType,(char)-1);
  Graphic_Form->setPropertyV(WSNvis,(WSCbool)1);
  Graphic_Form->setPropertyV(WSNanchorTop,(unsigned short)5);
  Graphic_Form->setPropertyV(WSNanchorBottom,(unsigned short)175);
  Graphic_Form->setPropertyV(WSNanchorLeft,(unsigned short)50);
  Graphic_Form->setPropertyV(WSNanchorRight,(unsigned short)140);
  Graphic_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Graphic_Form->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Graphic_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  Graphic_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  Describe_Form = new  WSCopenglForm(Graphic_Form,"Describe_Form");
      Describe_Form->initialize();
  Describe_Form->setPropertyV(WSNname,"Describe_Form");
  Describe_Form->setPropertyV(WSNx,(short)0);
  Describe_Form->setPropertyV(WSNy,(short)0);
  Describe_Form->setPropertyV(WSNwidth,(unsigned short)640);
  Describe_Form->setPropertyV(WSNheight,(unsigned short)480);
  Describe_Form->setPropertyV(WSNbackColor,"#000000");
  Describe_Form->setPropertyV(WSNtopShadowColor,"#282828");
  Describe_Form->setPropertyV(WSNbottomShadowColor,"#000000");
  Describe_Form->setPropertyV(WSNshadowType,(char)3);
  Describe_Form->setPropertyV(WSNvis,(WSCbool)1);
  Describe_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Describe_Form->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Describe_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  Describe_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);
    extern void Describe_Proc(WSCbase*);
    Describe_Form->addProcedureV("Describe_Proc","Describe_Proc",Describe_Proc,9);
    extern void Describe_Proc(WSCbase*);
    Describe_Form->addProcedureV("Describe_Proc","Describe_Proc",Describe_Proc,14);
    extern void Describe_Proc(WSCbase*);
    Describe_Form->addProcedureV("Describe_Proc","Describe_Proc",Describe_Proc,15);
    extern void Describe_Proc(WSCbase*);
    Describe_Form->addProcedureV("Describe_Proc","Describe_Proc",Describe_Proc,13);

  Menu_Form = new  WSCform(Kodatuno_Win,"Menu_Form");
      Menu_Form->initialize();
  Menu_Form->setPropertyV(WSNname,"Menu_Form");
  Menu_Form->setPropertyV(WSNx,(short)695);
  Menu_Form->setPropertyV(WSNy,(short)5);
  Menu_Form->setPropertyV(WSNwidth,(unsigned short)130);
  Menu_Form->setPropertyV(WSNheight,(unsigned short)480);
  Menu_Form->setPropertyV(WSNshadowType,(char)3);
  Menu_Form->setPropertyV(WSNvis,(WSCbool)1);
  Menu_Form->setPropertyV(WSNanchorTop,(unsigned short)5);
  Menu_Form->setPropertyV(WSNanchorBottom,(unsigned short)175);
  Menu_Form->setPropertyV(WSNanchorRight,(unsigned short)5);
  Menu_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Menu_Form->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Menu_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  Open_Body_Btn = new  WSCvbtn(Menu_Form,"Open_Body_Btn");
      Open_Body_Btn->initialize();
  Open_Body_Btn->setPropertyV(WSNuserValue,(long)1);
  Open_Body_Btn->setPropertyV(WSNusePixmap,(WSCbool)1);
  Open_Body_Btn->setPropertyV(WSNlabelString,"Open");
  Open_Body_Btn->setPropertyV(WSNname,"Open_Body_Btn");
  Open_Body_Btn->setPropertyV(WSNvis,(WSCbool)1);
  Open_Body_Btn->setPropertyV(WSNx,(short)5);
  Open_Body_Btn->setPropertyV(WSNy,(short)143);
  Open_Body_Btn->setPropertyV(WSNwidth,(unsigned short)58);
  Open_Body_Btn->setPropertyV(WSNheight,(unsigned short)25);
  Open_Body_Btn->setPropertyV(WSNanchorTop,(unsigned short)143);
  Open_Body_Btn->setPropertyV(WSNanchorLeft,(unsigned short)5);
  Open_Body_Btn->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Open_Body_Btn->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    Open_Body_Btn->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  User_Func_Btn5 = new  WSCvbtn(Menu_Form,"User_Func_Btn5");
      User_Func_Btn5->initialize();
  User_Func_Btn5->setPropertyV(WSNuserValue,(long)105);
  User_Func_Btn5->setPropertyV(WSNlabelString,"User Fucn 5");
  User_Func_Btn5->setPropertyV(WSNname,"User_Func_Btn5");
  User_Func_Btn5->setPropertyV(WSNvis,(WSCbool)1);
  User_Func_Btn5->setPropertyV(WSNx,(short)5);
  User_Func_Btn5->setPropertyV(WSNy,(short)445);
  User_Func_Btn5->setPropertyV(WSNwidth,(unsigned short)120);
  User_Func_Btn5->setPropertyV(WSNanchorBottom,(unsigned short)5);
  User_Func_Btn5->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Func_Btn5->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Func_Btn5->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Func_Btn5->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  User_Func_Btn4 = new  WSCvbtn(Menu_Form,"User_Func_Btn4");
      User_Func_Btn4->initialize();
  User_Func_Btn4->setPropertyV(WSNuserValue,(long)104);
  User_Func_Btn4->setPropertyV(WSNlabelString,"User Fucn 4");
  User_Func_Btn4->setPropertyV(WSNname,"User_Func_Btn4");
  User_Func_Btn4->setPropertyV(WSNvis,(WSCbool)1);
  User_Func_Btn4->setPropertyV(WSNx,(short)5);
  User_Func_Btn4->setPropertyV(WSNy,(short)415);
  User_Func_Btn4->setPropertyV(WSNwidth,(unsigned short)120);
  User_Func_Btn4->setPropertyV(WSNanchorBottom,(unsigned short)35);
  User_Func_Btn4->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Func_Btn4->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Func_Btn4->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Func_Btn4->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  User_Func_Btn3 = new  WSCvbtn(Menu_Form,"User_Func_Btn3");
      User_Func_Btn3->initialize();
  User_Func_Btn3->setPropertyV(WSNuserValue,(long)103);
  User_Func_Btn3->setPropertyV(WSNlabelString,"User Fucn 3");
  User_Func_Btn3->setPropertyV(WSNname,"User_Func_Btn3");
  User_Func_Btn3->setPropertyV(WSNvis,(WSCbool)1);
  User_Func_Btn3->setPropertyV(WSNx,(short)5);
  User_Func_Btn3->setPropertyV(WSNy,(short)385);
  User_Func_Btn3->setPropertyV(WSNwidth,(unsigned short)120);
  User_Func_Btn3->setPropertyV(WSNanchorBottom,(unsigned short)65);
  User_Func_Btn3->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Func_Btn3->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Func_Btn3->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Func_Btn3->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  User_Func_Btn2 = new  WSCvbtn(Menu_Form,"User_Func_Btn2");
      User_Func_Btn2->initialize();
  User_Func_Btn2->setPropertyV(WSNuserValue,(long)102);
  User_Func_Btn2->setPropertyV(WSNlabelString,"User Func 2");
  User_Func_Btn2->setPropertyV(WSNname,"User_Func_Btn2");
  User_Func_Btn2->setPropertyV(WSNvis,(WSCbool)1);
  User_Func_Btn2->setPropertyV(WSNx,(short)5);
  User_Func_Btn2->setPropertyV(WSNy,(short)355);
  User_Func_Btn2->setPropertyV(WSNwidth,(unsigned short)120);
  User_Func_Btn2->setPropertyV(WSNanchorBottom,(unsigned short)95);
  User_Func_Btn2->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Func_Btn2->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Func_Btn2->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Func_Btn2->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  User_Func_Btn1 = new  WSCvbtn(Menu_Form,"User_Func_Btn1");
      User_Func_Btn1->initialize();
  User_Func_Btn1->setPropertyV(WSNuserValue,(long)101);
  User_Func_Btn1->setPropertyV(WSNlabelString,"User Fucn 1");
  User_Func_Btn1->setPropertyV(WSNname,"User_Func_Btn1");
  User_Func_Btn1->setPropertyV(WSNvis,(WSCbool)1);
  User_Func_Btn1->setPropertyV(WSNx,(short)5);
  User_Func_Btn1->setPropertyV(WSNy,(short)325);
  User_Func_Btn1->setPropertyV(WSNwidth,(unsigned short)120);
  User_Func_Btn1->setPropertyV(WSNanchorBottom,(unsigned short)125);
  User_Func_Btn1->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Func_Btn1->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Func_Btn1->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Func_Btn1->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  Del_Body_Btn = new  WSCvbtn(Menu_Form,"Del_Body_Btn");
      Del_Body_Btn->initialize();
  Del_Body_Btn->setPropertyV(WSNuserValue,(long)2);
  Del_Body_Btn->setPropertyV(WSNlabelString,"Delete");
  Del_Body_Btn->setPropertyV(WSNname,"Del_Body_Btn");
  Del_Body_Btn->setPropertyV(WSNvis,(WSCbool)1);
  Del_Body_Btn->setPropertyV(WSNdet,(WSCbool)0);
  Del_Body_Btn->setPropertyV(WSNx,(short)67);
  Del_Body_Btn->setPropertyV(WSNy,(short)143);
  Del_Body_Btn->setPropertyV(WSNwidth,(unsigned short)58);
  Del_Body_Btn->setPropertyV(WSNheight,(unsigned short)25);
  Del_Body_Btn->setPropertyV(WSNanchorTop,(unsigned short)143);
  Del_Body_Btn->setPropertyV(WSNanchorLeft,(unsigned short)67);
  Del_Body_Btn->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Del_Body_Btn->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    Del_Body_Btn->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  Body_List_Win = new  WSClist(Menu_Form,"Body_List_Win");
      Body_List_Win->initialize();
  Body_List_Win->setPropertyV(WSNtitleString,"title2");
  Body_List_Win->setPropertyV(WSNbarThickness,(unsigned short)15);
  Body_List_Win->setPropertyV(WSNworkWidth,(unsigned short)200);
  Body_List_Win->setPropertyV(WSNworkHeight,(unsigned short)116);
  Body_List_Win->setPropertyV(WSNhbarVisible,(WSCbool)1);
  Body_List_Win->setPropertyV(WSNvbarVisible,(WSCbool)0);
  Body_List_Win->setPropertyV(WSNname,"Body_List_Win");
  Body_List_Win->setPropertyV(WSNx,(short)5);
  Body_List_Win->setPropertyV(WSNy,(short)5);
  Body_List_Win->setPropertyV(WSNwidth,(unsigned short)120);
  Body_List_Win->setPropertyV(WSNheight,(unsigned short)135);
  Body_List_Win->setPropertyV(WSNshadowThickness,(unsigned char)0);
  Body_List_Win->setPropertyV(WSNvis,(WSCbool)1);
  Body_List_Win->setPropertyV(WSNanchorTop,(unsigned short)5);
  Body_List_Win->setPropertyV(WSNanchorLeft,(unsigned short)5);
  Body_List_Win->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Body_List_Win->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void BodyListSel_Proc(WSCbase*);
    Body_List_Win->addProcedureV("BodyListSel_Proc","BodyListSel_Proc",BodyListSel_Proc,35);

  User_Stat_Btn = new  WSCvbtn(Menu_Form,"User_Stat_Btn");
      User_Stat_Btn->initialize();
  User_Stat_Btn->setPropertyV(WSNuserValue,(long)100);
  User_Stat_Btn->setPropertyV(WSNlabelString,"User Status");
  User_Stat_Btn->setPropertyV(WSNname,"User_Stat_Btn");
  User_Stat_Btn->setPropertyV(WSNvis,(WSCbool)1);
  User_Stat_Btn->setPropertyV(WSNx,(short)5);
  User_Stat_Btn->setPropertyV(WSNy,(short)290);
  User_Stat_Btn->setPropertyV(WSNwidth,(unsigned short)120);
  User_Stat_Btn->setPropertyV(WSNanchorBottom,(unsigned short)160);
  User_Stat_Btn->setPropertyV(WSNanchorLeft,(unsigned short)5);
  User_Stat_Btn->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  User_Stat_Btn->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void Menu_Proc(WSCbase*);
    User_Stat_Btn->addProcedureV("Menu_Proc","Menu_Proc",Menu_Proc,2);

  Console_Form = new  WSCtextField(Kodatuno_Win,"Console_Form");
      Console_Form->initialize();
  Console_Form->setPropertyV(WSNname,"Console_Form");
  Console_Form->setPropertyV(WSNx,(short)50);
  Console_Form->setPropertyV(WSNy,(short)510);
  Console_Form->setPropertyV(WSNwidth,(unsigned short)775);
  Console_Form->setPropertyV(WSNheight,(unsigned short)145);
  Console_Form->setPropertyV(WSNvis,(WSCbool)1);
  Console_Form->setPropertyV(WSNanchorBottom,(unsigned short)5);
  Console_Form->setPropertyV(WSNanchorLeft,(unsigned short)50);
  Console_Form->setPropertyV(WSNanchorRight,(unsigned short)5);
  Console_Form->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Console_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  Console_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);
  Console_Form->setPropertyV(WSNenableFep,(unsigned char)0);
  Console_Form->setPropertyV(WSNnoHatch,(WSCbool)1);
  Console_Form->setPropertyV(WSNdisplayOnly,(WSCbool)1);
  Console_Form->setPropertyV(WSNemboss,(WSCbool)1);
    extern void Console_Proc(WSCbase*);
    Console_Form->addProcedureV("Console_Proc","Console_Proc",Console_Proc,18);
    extern void Console_Proc(WSCbase*);
    Console_Form->addProcedureV("Console_Proc","Console_Proc",Console_Proc,9);

  Label_1 = new  WSCvlabel(Kodatuno_Win,"Label_1");
      Label_1->initialize();
  Label_1->setPropertyV(WSNshadowType,(char)-1);
  Label_1->setPropertyV(WSNlabelString,"Console");
  Label_1->setPropertyV(WSNalignmentH,(unsigned char)0);
  Label_1->setPropertyV(WSNname,"Label_1");
  Label_1->setPropertyV(WSNvis,(WSCbool)1);
  Label_1->setPropertyV(WSNx,(short)50);
  Label_1->setPropertyV(WSNy,(short)490);
  Label_1->setPropertyV(WSNwidth,(unsigned short)60);
  Label_1->setPropertyV(WSNheight,(unsigned short)20);
  Label_1->setPropertyV(WSNanchorBottom,(unsigned short)150);
  Label_1->setPropertyV(WSNanchorLeft,(unsigned short)50);
  Label_1->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Label_1->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  Line = new  WSCvline(Kodatuno_Win,"Line");
      Line->initialize();
  Line->setPropertyV(WSNlineX,"0,2000");
  Line->setPropertyV(WSNlineY,"0,0");
  Line->setPropertyV(WSNname,"Line");
  Line->setPropertyV(WSNvis,(WSCbool)1);
  Line->setPropertyV(WSNx,(short)110);
  Line->setPropertyV(WSNy,(short)500);
  Line->setPropertyV(WSNwidth,(unsigned short)715);
  Line->setPropertyV(WSNheight,(unsigned short)2);
  Line->setPropertyV(WSNforeColor,"#646464");
  Line->setPropertyV(WSNanchorBottom,(unsigned short)158);
  Line->setPropertyV(WSNanchorLeft,(unsigned short)110);
  Line->setPropertyV(WSNanchorRight,(unsigned short)5);
  Line->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  Line->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  Line->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  View_Form = new  WSCform(Kodatuno_Win,"View_Form");
      View_Form->initialize();
  View_Form->setPropertyV(WSNname,"View_Form");
  View_Form->setPropertyV(WSNx,(short)5);
  View_Form->setPropertyV(WSNy,(short)5);
  View_Form->setPropertyV(WSNwidth,(unsigned short)40);
  View_Form->setPropertyV(WSNheight,(unsigned short)650);
  View_Form->setPropertyV(WSNbackColor,"#a0a0a0");
  View_Form->setPropertyV(WSNtopShadowColor,"DEF15");
  View_Form->setPropertyV(WSNbottomShadowColor,"DEF16");
  View_Form->setPropertyV(WSNshadowType,(char)3);
  View_Form->setPropertyV(WSNvis,(WSCbool)1);
  View_Form->setPropertyV(WSNanchorTop,(unsigned short)5);
  View_Form->setPropertyV(WSNanchorBottom,(unsigned short)5);
  View_Form->setPropertyV(WSNanchorLeft,(unsigned short)5);
  View_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  View_Form->setPropertyV(WSNanchorBottomFlag,(WSCbool)1);
  View_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  ViewOnX = new  WSCvbtn(View_Form,"ViewOnX");
      ViewOnX->initialize();
  ViewOnX->setPropertyV(WSNuserValue,(long)1);
  ViewOnX->setPropertyV(WSNlabelPixmap,"./icons/ViewOnX.png");
  ViewOnX->setPropertyV(WSNname,"ViewOnX");
  ViewOnX->setPropertyV(WSNvis,(WSCbool)1);
  ViewOnX->setPropertyV(WSNx,(short)4);
  ViewOnX->setPropertyV(WSNy,(short)5);
  ViewOnX->setPropertyV(WSNwidth,(unsigned short)30);
  ViewOnX->setPropertyV(WSNanchorTop,(unsigned short)5);
  ViewOnX->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewOnX->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewOnX->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewOnX->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewOnY = new  WSCvbtn(View_Form,"ViewOnY");
      ViewOnY->initialize();
  ViewOnY->setPropertyV(WSNuserValue,(long)2);
  ViewOnY->setPropertyV(WSNlabelPixmap,"./icons/ViewOnY.png");
  ViewOnY->setPropertyV(WSNname,"ViewOnY");
  ViewOnY->setPropertyV(WSNvis,(WSCbool)1);
  ViewOnY->setPropertyV(WSNx,(short)4);
  ViewOnY->setPropertyV(WSNy,(short)35);
  ViewOnY->setPropertyV(WSNwidth,(unsigned short)30);
  ViewOnY->setPropertyV(WSNanchorTop,(unsigned short)35);
  ViewOnY->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewOnY->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewOnY->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewOnY->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewOnZ = new  WSCvbtn(View_Form,"ViewOnZ");
      ViewOnZ->initialize();
  ViewOnZ->setPropertyV(WSNuserValue,(long)3);
  ViewOnZ->setPropertyV(WSNlabelPixmap,"./icons/ViewOnZ.png");
  ViewOnZ->setPropertyV(WSNname,"ViewOnZ");
  ViewOnZ->setPropertyV(WSNvis,(WSCbool)1);
  ViewOnZ->setPropertyV(WSNx,(short)4);
  ViewOnZ->setPropertyV(WSNy,(short)65);
  ViewOnZ->setPropertyV(WSNwidth,(unsigned short)30);
  ViewOnZ->setPropertyV(WSNanchorTop,(unsigned short)65);
  ViewOnZ->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewOnZ->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewOnZ->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewOnZ->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewOnXYZ = new  WSCvbtn(View_Form,"ViewOnXYZ");
      ViewOnXYZ->initialize();
  ViewOnXYZ->setPropertyV(WSNuserValue,(long)4);
  ViewOnXYZ->setPropertyV(WSNlabelPixmap,"./icons/ViewOnXYZ.png");
  ViewOnXYZ->setPropertyV(WSNname,"ViewOnXYZ");
  ViewOnXYZ->setPropertyV(WSNvis,(WSCbool)1);
  ViewOnXYZ->setPropertyV(WSNx,(short)4);
  ViewOnXYZ->setPropertyV(WSNy,(short)95);
  ViewOnXYZ->setPropertyV(WSNwidth,(unsigned short)30);
  ViewOnXYZ->setPropertyV(WSNanchorTop,(unsigned short)95);
  ViewOnXYZ->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewOnXYZ->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewOnXYZ->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewOnXYZ->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewSolid = new  WSCvbtn(View_Form,"ViewSolid");
      ViewSolid->initialize();
  ViewSolid->setPropertyV(WSNuserValue,(long)10);
  ViewSolid->setPropertyV(WSNlabelPixmap,"./icons/ViewSolid.png");
  ViewSolid->setPropertyV(WSNname,"ViewSolid");
  ViewSolid->setPropertyV(WSNvis,(WSCbool)1);
  ViewSolid->setPropertyV(WSNx,(short)4);
  ViewSolid->setPropertyV(WSNy,(short)160);
  ViewSolid->setPropertyV(WSNwidth,(unsigned short)30);
  ViewSolid->setPropertyV(WSNanchorTop,(unsigned short)160);
  ViewSolid->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewSolid->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewSolid->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewSolid->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewWireFrame = new  WSCvbtn(View_Form,"ViewWireFrame");
      ViewWireFrame->initialize();
  ViewWireFrame->setPropertyV(WSNuserValue,(long)12);
  ViewWireFrame->setPropertyV(WSNlabelPixmap,"./icons/ViewWierFrame.png");
  ViewWireFrame->setPropertyV(WSNname,"ViewWireFrame");
  ViewWireFrame->setPropertyV(WSNvis,(WSCbool)1);
  ViewWireFrame->setPropertyV(WSNx,(short)4);
  ViewWireFrame->setPropertyV(WSNy,(short)220);
  ViewWireFrame->setPropertyV(WSNwidth,(unsigned short)30);
  ViewWireFrame->setPropertyV(WSNanchorTop,(unsigned short)220);
  ViewWireFrame->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewWireFrame->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewWireFrame->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewWireFrame->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewFit = new  WSCvbtn(View_Form,"ViewFit");
      ViewFit->initialize();
  ViewFit->setPropertyV(WSNuserValue,(long)5);
  ViewFit->setPropertyV(WSNlabelPixmap,"./icons/ViewFit.png");
  ViewFit->setPropertyV(WSNname,"ViewFit");
  ViewFit->setPropertyV(WSNvis,(WSCbool)1);
  ViewFit->setPropertyV(WSNx,(short)4);
  ViewFit->setPropertyV(WSNy,(short)125);
  ViewFit->setPropertyV(WSNwidth,(unsigned short)30);
  ViewFit->setPropertyV(WSNanchorTop,(unsigned short)125);
  ViewFit->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewFit->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewFit->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewFit->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewVoid = new  WSCvbtn(View_Form,"ViewVoid");
      ViewVoid->initialize();
  ViewVoid->setPropertyV(WSNuserValue,(long)13);
  ViewVoid->setPropertyV(WSNlabelPixmap,"./icons/ViewVoid.png");
  ViewVoid->setPropertyV(WSNname,"ViewVoid");
  ViewVoid->setPropertyV(WSNvis,(WSCbool)1);
  ViewVoid->setPropertyV(WSNx,(short)4);
  ViewVoid->setPropertyV(WSNy,(short)250);
  ViewVoid->setPropertyV(WSNwidth,(unsigned short)30);
  ViewVoid->setPropertyV(WSNanchorTop,(unsigned short)250);
  ViewVoid->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewVoid->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewVoid->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  SelectCancel = new  WSCvbtn(View_Form,"SelectCancel");
      SelectCancel->initialize();
  SelectCancel->setPropertyV(WSNuserValue,(long)101);
  SelectCancel->setPropertyV(WSNlabelPixmap,"./icons/SelectCancel.png");
  SelectCancel->setPropertyV(WSNname,"SelectCancel");
  SelectCancel->setPropertyV(WSNvis,(WSCbool)1);
  SelectCancel->setPropertyV(WSNx,(short)4);
  SelectCancel->setPropertyV(WSNy,(short)315);
  SelectCancel->setPropertyV(WSNwidth,(unsigned short)30);
  SelectCancel->setPropertyV(WSNanchorTop,(unsigned short)315);
  SelectCancel->setPropertyV(WSNanchorLeft,(unsigned short)4);
  SelectCancel->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  SelectCancel->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    SelectCancel->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewErase = new  WSCvbtn(View_Form,"ViewErase");
      ViewErase->initialize();
  ViewErase->setPropertyV(WSNuserValue,(long)102);
  ViewErase->setPropertyV(WSNlabelPixmap,"./icons/ViewErase.png");
  ViewErase->setPropertyV(WSNname,"ViewErase");
  ViewErase->setPropertyV(WSNvis,(WSCbool)1);
  ViewErase->setPropertyV(WSNx,(short)4);
  ViewErase->setPropertyV(WSNy,(short)345);
  ViewErase->setPropertyV(WSNwidth,(unsigned short)30);
  ViewErase->setPropertyV(WSNanchorTop,(unsigned short)345);
  ViewErase->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewErase->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewErase->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewErase->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewBlend = new  WSCvbtn(View_Form,"ViewBlend");
      ViewBlend->initialize();
  ViewBlend->setPropertyV(WSNuserValue,(long)1000);
  ViewBlend->setPropertyV(WSNlabelPixmap,"./icons/ViewBlend.png");
  ViewBlend->setPropertyV(WSNname,"ViewBlend");
  ViewBlend->setPropertyV(WSNvis,(WSCbool)1);
  ViewBlend->setPropertyV(WSNx,(short)4);
  ViewBlend->setPropertyV(WSNy,(short)380);
  ViewBlend->setPropertyV(WSNwidth,(unsigned short)30);
  ViewBlend->setPropertyV(WSNanchorTop,(unsigned short)380);
  ViewBlend->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewBlend->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewBlend->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewBlend->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  SelectAll = new  WSCvbtn(View_Form,"SelectAll");
      SelectAll->initialize();
  SelectAll->setPropertyV(WSNuserValue,(long)100);
  SelectAll->setPropertyV(WSNlabelPixmap,"./icons/SelectAll.png");
  SelectAll->setPropertyV(WSNname,"SelectAll");
  SelectAll->setPropertyV(WSNvis,(WSCbool)1);
  SelectAll->setPropertyV(WSNx,(short)4);
  SelectAll->setPropertyV(WSNy,(short)285);
  SelectAll->setPropertyV(WSNwidth,(unsigned short)30);
  SelectAll->setPropertyV(WSNanchorTop,(unsigned short)285);
  SelectAll->setPropertyV(WSNanchorLeft,(unsigned short)4);
  SelectAll->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  SelectAll->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    SelectAll->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  ViewNoEdge = new  WSCvbtn(View_Form,"ViewNoEdge");
      ViewNoEdge->initialize();
  ViewNoEdge->setPropertyV(WSNuserValue,(long)11);
  ViewNoEdge->setPropertyV(WSNlabelPixmap,"./icons/ViewSolid_NoEdge.png");
  ViewNoEdge->setPropertyV(WSNname,"ViewNoEdge");
  ViewNoEdge->setPropertyV(WSNvis,(WSCbool)1);
  ViewNoEdge->setPropertyV(WSNx,(short)4);
  ViewNoEdge->setPropertyV(WSNy,(short)190);
  ViewNoEdge->setPropertyV(WSNwidth,(unsigned short)30);
  ViewNoEdge->setPropertyV(WSNanchorTop,(unsigned short)190);
  ViewNoEdge->setPropertyV(WSNanchorLeft,(unsigned short)4);
  ViewNoEdge->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  ViewNoEdge->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void ChangeView_Proc(WSCbase*);
    ViewNoEdge->addProcedureV("ChangeView_Proc","ChangeView_Proc",ChangeView_Proc,2);

  RotSurf_Dlg = new  WSCdialog(Kodatuno_Win,"RotSurf_Dlg");
      RotSurf_Dlg->initialize();
  RotSurf_Dlg->setPropertyV(WSNworkBackColor,"DEF1");
  RotSurf_Dlg->setPropertyV(WSNno,(WSCbool)0);
  RotSurf_Dlg->setPropertyV(WSNname,"RotSurf_Dlg");
  RotSurf_Dlg->setPropertyV(WSNtitleString,"Roteting Surface Generation");
  RotSurf_Dlg->setPropertyV(WSNx,(short)300);
  RotSurf_Dlg->setPropertyV(WSNy,(short)320);
  RotSurf_Dlg->setPropertyV(WSNwidth,(unsigned short)400);
  RotSurf_Dlg->setPropertyV(WSNheight,(unsigned short)170);
  RotSurf_Dlg->setPropertyV(WSNtitleBar,(char)2);
    extern void RotSurfDlg_Proc(WSCbase*);
    RotSurf_Dlg->addProcedureV("RotSurfDlg","RotSurfDlg_Proc",RotSurfDlg_Proc,2);

  AxisOfRotation_Form = new  WSCtform(RotSurf_Dlg,"AxisOfRotation_Form");
      AxisOfRotation_Form->initialize();
  AxisOfRotation_Form->setPropertyV(WSNtitleString,"Rotation axis");
  AxisOfRotation_Form->setPropertyV(WSNname,"AxisOfRotation_Form");
  AxisOfRotation_Form->setPropertyV(WSNx,(short)3);
  AxisOfRotation_Form->setPropertyV(WSNy,(short)10);
  AxisOfRotation_Form->setPropertyV(WSNwidth,(unsigned short)390);
  AxisOfRotation_Form->setPropertyV(WSNheight,(unsigned short)53);
  AxisOfRotation_Form->setPropertyV(WSNvis,(WSCbool)1);
  AxisOfRotation_Form->setPropertyV(WSNanchorTop,(unsigned short)10);
  AxisOfRotation_Form->setPropertyV(WSNanchorLeft,(unsigned short)3);
  AxisOfRotation_Form->setPropertyV(WSNanchorRight,(unsigned short)7);
  AxisOfRotation_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AxisOfRotation_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  AxisOfRotation_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  AOR_Label_X = new  WSCvlabel(AxisOfRotation_Form,"AOR_Label_X");
      AOR_Label_X->initialize();
  AOR_Label_X->setPropertyV(WSNshadowType,(char)-1);
  AOR_Label_X->setPropertyV(WSNlabelString,"X");
  AOR_Label_X->setPropertyV(WSNname,"AOR_Label_X");
  AOR_Label_X->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Label_X->setPropertyV(WSNx,(short)10);
  AOR_Label_X->setPropertyV(WSNy,(short)20);
  AOR_Label_X->setPropertyV(WSNwidth,(unsigned short)20);
  AOR_Label_X->setPropertyV(WSNheight,(unsigned short)20);
  AOR_Label_X->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Label_X->setPropertyV(WSNanchorLeft,(unsigned short)10);
  AOR_Label_X->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Label_X->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  AOR_Label_Y = new  WSCvlabel(AxisOfRotation_Form,"AOR_Label_Y");
      AOR_Label_Y->initialize();
  AOR_Label_Y->setPropertyV(WSNshadowType,(char)-1);
  AOR_Label_Y->setPropertyV(WSNlabelString,"Y");
  AOR_Label_Y->setPropertyV(WSNname,"AOR_Label_Y");
  AOR_Label_Y->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Label_Y->setPropertyV(WSNx,(short)132);
  AOR_Label_Y->setPropertyV(WSNy,(short)20);
  AOR_Label_Y->setPropertyV(WSNwidth,(unsigned short)20);
  AOR_Label_Y->setPropertyV(WSNheight,(unsigned short)20);
  AOR_Label_Y->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Label_Y->setPropertyV(WSNanchorLeft,(unsigned short)132);
  AOR_Label_Y->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Label_Y->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  AOR_Label_Z = new  WSCvlabel(AxisOfRotation_Form,"AOR_Label_Z");
      AOR_Label_Z->initialize();
  AOR_Label_Z->setPropertyV(WSNshadowType,(char)-1);
  AOR_Label_Z->setPropertyV(WSNlabelString,"Z");
  AOR_Label_Z->setPropertyV(WSNname,"AOR_Label_Z");
  AOR_Label_Z->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Label_Z->setPropertyV(WSNx,(short)254);
  AOR_Label_Z->setPropertyV(WSNy,(short)20);
  AOR_Label_Z->setPropertyV(WSNwidth,(unsigned short)20);
  AOR_Label_Z->setPropertyV(WSNheight,(unsigned short)20);
  AOR_Label_Z->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Label_Z->setPropertyV(WSNanchorLeft,(unsigned short)254);
  AOR_Label_Z->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Label_Z->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  AOR_X = new  WSCvifield(AxisOfRotation_Form,"AOR_X");
      AOR_X->initialize();
  AOR_X->setPropertyV(WSNenableFep,(unsigned char)0);
  AOR_X->setPropertyV(WSNtab,"AOR_Y");
  AOR_X->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  AOR_X->setPropertyV(WSNemboss,(WSCbool)1);
  AOR_X->setPropertyV(WSNlabelString,"0.0");
  AOR_X->setPropertyV(WSNname,"AOR_X");
  AOR_X->setPropertyV(WSNvis,(WSCbool)1);
  AOR_X->setPropertyV(WSNx,(short)30);
  AOR_X->setPropertyV(WSNy,(short)20);
  AOR_X->setPropertyV(WSNheight,(unsigned short)25);
  AOR_X->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_X->setPropertyV(WSNanchorLeft,(unsigned short)30);
  AOR_X->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_X->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  AOR_Y = new  WSCvifield(AxisOfRotation_Form,"AOR_Y");
      AOR_Y->initialize();
  AOR_Y->setPropertyV(WSNenableFep,(unsigned char)0);
  AOR_Y->setPropertyV(WSNtab,"AOR_Z");
  AOR_Y->setPropertyV(WSNbacktab,"AOR_X");
  AOR_Y->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  AOR_Y->setPropertyV(WSNemboss,(WSCbool)1);
  AOR_Y->setPropertyV(WSNlabelString,"0.0");
  AOR_Y->setPropertyV(WSNname,"AOR_Y");
  AOR_Y->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Y->setPropertyV(WSNx,(short)152);
  AOR_Y->setPropertyV(WSNy,(short)20);
  AOR_Y->setPropertyV(WSNheight,(unsigned short)25);
  AOR_Y->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Y->setPropertyV(WSNanchorLeft,(unsigned short)152);
  AOR_Y->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Y->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  AOR_Z = new  WSCvifield(AxisOfRotation_Form,"AOR_Z");
      AOR_Z->initialize();
  AOR_Z->setPropertyV(WSNenableFep,(unsigned char)0);
  AOR_Z->setPropertyV(WSNtab,"AOR_Ang");
  AOR_Z->setPropertyV(WSNbacktab,"AOR_Y");
  AOR_Z->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  AOR_Z->setPropertyV(WSNemboss,(WSCbool)1);
  AOR_Z->setPropertyV(WSNlabelString,"1.0");
  AOR_Z->setPropertyV(WSNname,"AOR_Z");
  AOR_Z->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Z->setPropertyV(WSNx,(short)274);
  AOR_Z->setPropertyV(WSNy,(short)20);
  AOR_Z->setPropertyV(WSNheight,(unsigned short)25);
  AOR_Z->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Z->setPropertyV(WSNanchorLeft,(unsigned short)274);
  AOR_Z->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Z->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  RotAng_Form = new  WSCtform(RotSurf_Dlg,"RotAng_Form");
      RotAng_Form->initialize();
  RotAng_Form->setPropertyV(WSNtitleString,"Rotation angle");
  RotAng_Form->setPropertyV(WSNname,"RotAng_Form");
  RotAng_Form->setPropertyV(WSNx,(short)3);
  RotAng_Form->setPropertyV(WSNy,(short)70);
  RotAng_Form->setPropertyV(WSNwidth,(unsigned short)147);
  RotAng_Form->setPropertyV(WSNheight,(unsigned short)53);
  RotAng_Form->setPropertyV(WSNvis,(WSCbool)1);
  RotAng_Form->setPropertyV(WSNanchorTop,(unsigned short)70);
  RotAng_Form->setPropertyV(WSNanchorLeft,(unsigned short)3);
  RotAng_Form->setPropertyV(WSNanchorRight,(unsigned short)250);
  RotAng_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  RotAng_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  RotAng_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  AOR_Ang = new  WSCvifield(RotAng_Form,"AOR_Ang");
      AOR_Ang->initialize();
  AOR_Ang->setPropertyV(WSNenableFep,(unsigned char)0);
  AOR_Ang->setPropertyV(WSNtab,"RotSurf_Dlg");
  AOR_Ang->setPropertyV(WSNbacktab,"AOR_Z");
  AOR_Ang->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  AOR_Ang->setPropertyV(WSNemboss,(WSCbool)1);
  AOR_Ang->setPropertyV(WSNlabelString,"360.0");
  AOR_Ang->setPropertyV(WSNname,"AOR_Ang");
  AOR_Ang->setPropertyV(WSNvis,(WSCbool)1);
  AOR_Ang->setPropertyV(WSNx,(short)10);
  AOR_Ang->setPropertyV(WSNy,(short)20);
  AOR_Ang->setPropertyV(WSNwidth,(unsigned short)132);
  AOR_Ang->setPropertyV(WSNheight,(unsigned short)25);
  AOR_Ang->setPropertyV(WSNanchorTop,(unsigned short)20);
  AOR_Ang->setPropertyV(WSNanchorLeft,(unsigned short)10);
  AOR_Ang->setPropertyV(WSNanchorRight,(unsigned short)5);
  AOR_Ang->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  AOR_Ang->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  AOR_Ang->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  NurbsCurve_Dlg = new  WSCdialog(Kodatuno_Win,"NurbsCurve_Dlg");
      NurbsCurve_Dlg->initialize();
  NurbsCurve_Dlg->setPropertyV(WSNworkBackColor,"DEF1");
  NurbsCurve_Dlg->setPropertyV(WSNno,(WSCbool)0);
  NurbsCurve_Dlg->setPropertyV(WSNname,"NurbsCurve_Dlg");
  NurbsCurve_Dlg->setPropertyV(WSNtitleString,"Nurbs Curve Generator");
  NurbsCurve_Dlg->setPropertyV(WSNx,(short)300);
  NurbsCurve_Dlg->setPropertyV(WSNy,(short)320);
  NurbsCurve_Dlg->setPropertyV(WSNwidth,(unsigned short)200);
  NurbsCurve_Dlg->setPropertyV(WSNheight,(unsigned short)237);
  NurbsCurve_Dlg->setPropertyV(WSNtitleBar,(char)2);
    extern void NurbsCDlg_Proc(WSCbase*);
    NurbsCurve_Dlg->addProcedureV("NurbsCDlg","NurbsCDlg_Proc",NurbsCDlg_Proc,2);

  NurbsCOpt = new  WSCradioGroup(NurbsCurve_Dlg,"NurbsCOpt");
      NurbsCOpt->initialize();
  NurbsCOpt->setPropertyV(WSNmenuItems,"Polygonal,Interpolated 1,Approximated,Inerpolated 2,Control Point");
  NurbsCOpt->setPropertyV(WSNvalue,(unsigned long)5);
  NurbsCOpt->setPropertyV(WSNtitleString,"Option");
  NurbsCOpt->setPropertyV(WSNname,"NurbsCOpt");
  NurbsCOpt->setPropertyV(WSNx,(short)3);
  NurbsCOpt->setPropertyV(WSNy,(short)10);
  NurbsCOpt->setPropertyV(WSNwidth,(unsigned short)190);
  NurbsCOpt->setPropertyV(WSNheight,(unsigned short)150);
  NurbsCOpt->setPropertyV(WSNvis,(WSCbool)1);
  NurbsCOpt->setPropertyV(WSNanchorTop,(unsigned short)10);
  NurbsCOpt->setPropertyV(WSNanchorLeft,(unsigned short)3);
  NurbsCOpt->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  NurbsCOpt->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  OpenInpFile_Btn = new  WSCvbtn(NurbsCurve_Dlg,"OpenInpFile_Btn");
      OpenInpFile_Btn->initialize();
  OpenInpFile_Btn->setPropertyV(WSNlabelString,"File");
  OpenInpFile_Btn->setPropertyV(WSNname,"OpenInpFile_Btn");
  OpenInpFile_Btn->setPropertyV(WSNvis,(WSCbool)1);
  OpenInpFile_Btn->setPropertyV(WSNx,(short)8);
  OpenInpFile_Btn->setPropertyV(WSNy,(short)170);
  OpenInpFile_Btn->setPropertyV(WSNwidth,(unsigned short)70);
  OpenInpFile_Btn->setPropertyV(WSNheight,(unsigned short)25);
  OpenInpFile_Btn->setPropertyV(WSNanchorTop,(unsigned short)170);
  OpenInpFile_Btn->setPropertyV(WSNanchorLeft,(unsigned short)8);
  OpenInpFile_Btn->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  OpenInpFile_Btn->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void OpenInpFile_Proc(WSCbase*);
    OpenInpFile_Btn->addProcedureV("OpenInpFile_Proc","OpenInpFile_Proc",OpenInpFile_Proc,2);

  InpFileName = new  WSCvifield(NurbsCurve_Dlg,"InpFileName");
      InpFileName->initialize();
  InpFileName->setPropertyV(WSNenableFep,(unsigned char)0);
  InpFileName->setPropertyV(WSNemboss,(WSCbool)1);
  InpFileName->setPropertyV(WSNmaxLength,(unsigned short)256);
  InpFileName->setPropertyV(WSNname,"InpFileName");
  InpFileName->setPropertyV(WSNdet,(WSCbool)0);
  InpFileName->setPropertyV(WSNx,(short)3);
  InpFileName->setPropertyV(WSNy,(short)170);
  InpFileName->setPropertyV(WSNwidth,(unsigned short)0);

  NurbsC_Rank_Lb = new  WSCvlabel(NurbsCurve_Dlg,"NurbsC_Rank_Lb");
      NurbsC_Rank_Lb->initialize();
  NurbsC_Rank_Lb->setPropertyV(WSNshadowType,(char)-1);
  NurbsC_Rank_Lb->setPropertyV(WSNlabelString,"Rank");
  NurbsC_Rank_Lb->setPropertyV(WSNalignmentH,(unsigned char)1);
  NurbsC_Rank_Lb->setPropertyV(WSNname,"NurbsC_Rank_Lb");
  NurbsC_Rank_Lb->setPropertyV(WSNvis,(WSCbool)1);
  NurbsC_Rank_Lb->setPropertyV(WSNx,(short)110);
  NurbsC_Rank_Lb->setPropertyV(WSNy,(short)170);
  NurbsC_Rank_Lb->setPropertyV(WSNwidth,(unsigned short)35);

  NurbsC_Rank = new  WSCvifield(NurbsCurve_Dlg,"NurbsC_Rank");
      NurbsC_Rank->initialize();
  NurbsC_Rank->setPropertyV(WSNenableFep,(unsigned char)0);
  NurbsC_Rank->setPropertyV(WSNshadowType,(char)2);
  NurbsC_Rank->setPropertyV(WSNemboss,(WSCbool)1);
  NurbsC_Rank->setPropertyV(WSNlabelString,"4");
  NurbsC_Rank->setPropertyV(WSNname,"NurbsC_Rank");
  NurbsC_Rank->setPropertyV(WSNvis,(WSCbool)1);
  NurbsC_Rank->setPropertyV(WSNx,(short)150);
  NurbsC_Rank->setPropertyV(WSNy,(short)170);
  NurbsC_Rank->setPropertyV(WSNwidth,(unsigned short)30);
  NurbsC_Rank->setPropertyV(WSNheight,(unsigned short)25);
  NurbsC_Rank->setPropertyV(WSNanchorTop,(unsigned short)170);
  NurbsC_Rank->setPropertyV(WSNanchorLeft,(unsigned short)150);
  NurbsC_Rank->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  NurbsC_Rank->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  User_Stat_Dlg = new  WSCdialog(Kodatuno_Win,"User_Stat_Dlg");
      User_Stat_Dlg->initialize();
  User_Stat_Dlg->setPropertyV(WSNno,(WSCbool)0);
  User_Stat_Dlg->setPropertyV(WSNname,"User_Stat_Dlg");
  User_Stat_Dlg->setPropertyV(WSNtitleString,"User_Dlg");
  User_Stat_Dlg->setPropertyV(WSNx,(short)300);
  User_Stat_Dlg->setPropertyV(WSNy,(short)320);
  User_Stat_Dlg->setPropertyV(WSNwidth,(unsigned short)355);
  User_Stat_Dlg->setPropertyV(WSNheight,(unsigned short)366);
  User_Stat_Dlg->setPropertyV(WSNtitleBar,(char)2);
    extern void UserStatDlg_Proc(WSCbase*);
    User_Stat_Dlg->addProcedureV("UserStatDlg","UserStatDlg_Proc",UserStatDlg_Proc,2);

  Uer_Prop1_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop1_Lab");
      Uer_Prop1_Lab->initialize();
  Uer_Prop1_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop1_Lab->setPropertyV(WSNlabelString,"Prop1");
  Uer_Prop1_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop1_Lab->setPropertyV(WSNname,"Uer_Prop1_Lab");
  Uer_Prop1_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop1_Lab->setPropertyV(WSNx,(short)10);
  Uer_Prop1_Lab->setPropertyV(WSNy,(short)172);
  Uer_Prop1_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop2_Lab = new  WSCvlabel(User_Stat_Dlg,"User_Prop2_Lab");
      User_Prop2_Lab->initialize();
  User_Prop2_Lab->setPropertyV(WSNshadowType,(char)-1);
  User_Prop2_Lab->setPropertyV(WSNlabelString,"Prop2");
  User_Prop2_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  User_Prop2_Lab->setPropertyV(WSNname,"User_Prop2_Lab");
  User_Prop2_Lab->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop2_Lab->setPropertyV(WSNx,(short)10);
  User_Prop2_Lab->setPropertyV(WSNy,(short)200);
  User_Prop2_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop1 = new  WSCvifield(User_Stat_Dlg,"User_Prop1");
      User_Prop1->initialize();
  User_Prop1->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop1->setPropertyV(WSNtab,"User_Prop2");
  User_Prop1->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop1->setPropertyV(WSNshadowType,(char)1);
  User_Prop1->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop1->setPropertyV(WSNlabelString,"0");
  User_Prop1->setPropertyV(WSNname,"User_Prop1");
  User_Prop1->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop1->setPropertyV(WSNx,(short)55);
  User_Prop1->setPropertyV(WSNy,(short)172);
  User_Prop1->setPropertyV(WSNwidth,(unsigned short)58);
  User_Prop1->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop2 = new  WSCvifield(User_Stat_Dlg,"User_Prop2");
      User_Prop2->initialize();
  User_Prop2->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop2->setPropertyV(WSNtab,"User_Prop3");
  User_Prop2->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop2->setPropertyV(WSNshadowType,(char)1);
  User_Prop2->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop2->setPropertyV(WSNlabelString,"-10");
  User_Prop2->setPropertyV(WSNname,"User_Prop2");
  User_Prop2->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop2->setPropertyV(WSNx,(short)55);
  User_Prop2->setPropertyV(WSNy,(short)202);
  User_Prop2->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop2->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop3_Lab = new  WSCvlabel(User_Stat_Dlg,"User_Prop3_Lab");
      User_Prop3_Lab->initialize();
  User_Prop3_Lab->setPropertyV(WSNshadowType,(char)-1);
  User_Prop3_Lab->setPropertyV(WSNlabelString,"Prop3");
  User_Prop3_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  User_Prop3_Lab->setPropertyV(WSNname,"User_Prop3_Lab");
  User_Prop3_Lab->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop3_Lab->setPropertyV(WSNx,(short)10);
  User_Prop3_Lab->setPropertyV(WSNy,(short)230);
  User_Prop3_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop4_Lab = new  WSCvlabel(User_Stat_Dlg,"User_Prop4_Lab");
      User_Prop4_Lab->initialize();
  User_Prop4_Lab->setPropertyV(WSNshadowType,(char)-1);
  User_Prop4_Lab->setPropertyV(WSNlabelString,"Prop4");
  User_Prop4_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  User_Prop4_Lab->setPropertyV(WSNname,"User_Prop4_Lab");
  User_Prop4_Lab->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop4_Lab->setPropertyV(WSNx,(short)10);
  User_Prop4_Lab->setPropertyV(WSNy,(short)260);
  User_Prop4_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop5_Lab = new  WSCvlabel(User_Stat_Dlg,"User_Prop5_Lab");
      User_Prop5_Lab->initialize();
  User_Prop5_Lab->setPropertyV(WSNshadowType,(char)-1);
  User_Prop5_Lab->setPropertyV(WSNlabelString,"Prop5");
  User_Prop5_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  User_Prop5_Lab->setPropertyV(WSNname,"User_Prop5_Lab");
  User_Prop5_Lab->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop5_Lab->setPropertyV(WSNx,(short)10);
  User_Prop5_Lab->setPropertyV(WSNy,(short)290);
  User_Prop5_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop3 = new  WSCvifield(User_Stat_Dlg,"User_Prop3");
      User_Prop3->initialize();
  User_Prop3->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop3->setPropertyV(WSNtab,"User_Prop4");
  User_Prop3->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop3->setPropertyV(WSNshadowType,(char)1);
  User_Prop3->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop3->setPropertyV(WSNlabelString,"1");
  User_Prop3->setPropertyV(WSNname,"User_Prop3");
  User_Prop3->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop3->setPropertyV(WSNx,(short)55);
  User_Prop3->setPropertyV(WSNy,(short)232);
  User_Prop3->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop3->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop4 = new  WSCvifield(User_Stat_Dlg,"User_Prop4");
      User_Prop4->initialize();
  User_Prop4->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop4->setPropertyV(WSNtab,"User_Prop5");
  User_Prop4->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop4->setPropertyV(WSNshadowType,(char)1);
  User_Prop4->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop4->setPropertyV(WSNlabelString,"0.1");
  User_Prop4->setPropertyV(WSNname,"User_Prop4");
  User_Prop4->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop4->setPropertyV(WSNx,(short)55);
  User_Prop4->setPropertyV(WSNy,(short)262);
  User_Prop4->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop4->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop5 = new  WSCvifield(User_Stat_Dlg,"User_Prop5");
      User_Prop5->initialize();
  User_Prop5->setPropertyV(WSNtab,"User_Prop6");
  User_Prop5->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop5->setPropertyV(WSNshadowType,(char)1);
  User_Prop5->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop5->setPropertyV(WSNlabelString,"0");
  User_Prop5->setPropertyV(WSNname,"User_Prop5");
  User_Prop5->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop5->setPropertyV(WSNx,(short)55);
  User_Prop5->setPropertyV(WSNy,(short)292);
  User_Prop5->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop5->setPropertyV(WSNheight,(unsigned short)25);

  Uer_Prop7_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop7_Lab");
      Uer_Prop7_Lab->initialize();
  Uer_Prop7_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop7_Lab->setPropertyV(WSNlabelString,"Prop7");
  Uer_Prop7_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop7_Lab->setPropertyV(WSNname,"Uer_Prop7_Lab");
  Uer_Prop7_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop7_Lab->setPropertyV(WSNx,(short)125);
  Uer_Prop7_Lab->setPropertyV(WSNy,(short)202);
  Uer_Prop7_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop8_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop8_Lab");
      Uer_Prop8_Lab->initialize();
  Uer_Prop8_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop8_Lab->setPropertyV(WSNlabelString,"Prop8");
  Uer_Prop8_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop8_Lab->setPropertyV(WSNname,"Uer_Prop8_Lab");
  Uer_Prop8_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop8_Lab->setPropertyV(WSNx,(short)125);
  Uer_Prop8_Lab->setPropertyV(WSNy,(short)232);
  Uer_Prop8_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop9_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop9_Lab");
      Uer_Prop9_Lab->initialize();
  Uer_Prop9_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop9_Lab->setPropertyV(WSNlabelString,"Prop9");
  Uer_Prop9_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop9_Lab->setPropertyV(WSNname,"Uer_Prop9_Lab");
  Uer_Prop9_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop9_Lab->setPropertyV(WSNx,(short)125);
  Uer_Prop9_Lab->setPropertyV(WSNy,(short)262);
  Uer_Prop9_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop10_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop10_Lab");
      Uer_Prop10_Lab->initialize();
  Uer_Prop10_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop10_Lab->setPropertyV(WSNlabelString,"Prop10");
  Uer_Prop10_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop10_Lab->setPropertyV(WSNname,"Uer_Prop10_Lab");
  Uer_Prop10_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop10_Lab->setPropertyV(WSNx,(short)125);
  Uer_Prop10_Lab->setPropertyV(WSNy,(short)292);
  Uer_Prop10_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop6 = new  WSCvifield(User_Stat_Dlg,"User_Prop6");
      User_Prop6->initialize();
  User_Prop6->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop6->setPropertyV(WSNtab,"User_Prop7");
  User_Prop6->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop6->setPropertyV(WSNshadowType,(char)1);
  User_Prop6->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop6->setPropertyV(WSNlabelString,"0");
  User_Prop6->setPropertyV(WSNname,"User_Prop6");
  User_Prop6->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop6->setPropertyV(WSNx,(short)170);
  User_Prop6->setPropertyV(WSNy,(short)172);
  User_Prop6->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop6->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop7 = new  WSCvifield(User_Stat_Dlg,"User_Prop7");
      User_Prop7->initialize();
  User_Prop7->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop7->setPropertyV(WSNtab,"User_Prop8");
  User_Prop7->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop7->setPropertyV(WSNshadowType,(char)1);
  User_Prop7->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop7->setPropertyV(WSNlabelString,"0");
  User_Prop7->setPropertyV(WSNname,"User_Prop7");
  User_Prop7->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop7->setPropertyV(WSNx,(short)170);
  User_Prop7->setPropertyV(WSNy,(short)202);
  User_Prop7->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop7->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop8 = new  WSCvifield(User_Stat_Dlg,"User_Prop8");
      User_Prop8->initialize();
  User_Prop8->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop8->setPropertyV(WSNtab,"User_Prop9");
  User_Prop8->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop8->setPropertyV(WSNshadowType,(char)1);
  User_Prop8->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop8->setPropertyV(WSNlabelString,"0");
  User_Prop8->setPropertyV(WSNname,"User_Prop8");
  User_Prop8->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop8->setPropertyV(WSNx,(short)170);
  User_Prop8->setPropertyV(WSNy,(short)232);
  User_Prop8->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop8->setPropertyV(WSNheight,(unsigned short)26);

  User_Prop9 = new  WSCvifield(User_Stat_Dlg,"User_Prop9");
      User_Prop9->initialize();
  User_Prop9->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop9->setPropertyV(WSNtab,"User_Prop10");
  User_Prop9->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop9->setPropertyV(WSNshadowType,(char)1);
  User_Prop9->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop9->setPropertyV(WSNlabelString,"0");
  User_Prop9->setPropertyV(WSNname,"User_Prop9");
  User_Prop9->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop9->setPropertyV(WSNx,(short)170);
  User_Prop9->setPropertyV(WSNy,(short)262);
  User_Prop9->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop9->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop10 = new  WSCvifield(User_Stat_Dlg,"User_Prop10");
      User_Prop10->initialize();
  User_Prop10->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop10->setPropertyV(WSNtab,"User_Prop1");
  User_Prop10->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop10->setPropertyV(WSNshadowType,(char)1);
  User_Prop10->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop10->setPropertyV(WSNlabelString,"0");
  User_Prop10->setPropertyV(WSNname,"User_Prop10");
  User_Prop10->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop10->setPropertyV(WSNx,(short)170);
  User_Prop10->setPropertyV(WSNy,(short)292);
  User_Prop10->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop10->setPropertyV(WSNheight,(unsigned short)25);

  UerMode = new  WSCtform(User_Stat_Dlg,"UerMode");
      UerMode->initialize();
  UerMode->setPropertyV(WSNtitleString,"Mode");
  UerMode->setPropertyV(WSNname,"UerMode");
  UerMode->setPropertyV(WSNx,(short)10);
  UerMode->setPropertyV(WSNy,(short)10);
  UerMode->setPropertyV(WSNwidth,(unsigned short)325);
  UerMode->setPropertyV(WSNheight,(unsigned short)150);
  UerMode->setPropertyV(WSNbackColor,"DEF5");
  UerMode->setPropertyV(WSNvis,(WSCbool)1);

  UserMode1 = new  WSCvradio(UerMode,"UserMode1");
      UserMode1->initialize();
  UserMode1->setPropertyV(WSNunique,(WSCbool)1);
  UserMode1->setPropertyV(WSNgroup,"UserMode");
  UserMode1->setPropertyV(WSNlabelString,"Mode1");
  UserMode1->setPropertyV(WSNname,"UserMode1");
  UserMode1->setPropertyV(WSNvis,(WSCbool)1);
  UserMode1->setPropertyV(WSNx,(short)15);
  UserMode1->setPropertyV(WSNy,(short)20);
  UserMode1->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode1->setPropertyV(WSNheight,(unsigned short)25);

  UserMode2 = new  WSCvradio(UerMode,"UserMode2");
      UserMode2->initialize();
  UserMode2->setPropertyV(WSNunique,(WSCbool)1);
  UserMode2->setPropertyV(WSNgroup,"UserMode");
  UserMode2->setPropertyV(WSNid,(short)1);
  UserMode2->setPropertyV(WSNlabelString,"Mode2");
  UserMode2->setPropertyV(WSNname,"UserMode2");
  UserMode2->setPropertyV(WSNvis,(WSCbool)1);
  UserMode2->setPropertyV(WSNx,(short)15);
  UserMode2->setPropertyV(WSNy,(short)45);
  UserMode2->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode2->setPropertyV(WSNheight,(unsigned short)25);

  UserMode3 = new  WSCvradio(UerMode,"UserMode3");
      UserMode3->initialize();
  UserMode3->setPropertyV(WSNunique,(WSCbool)1);
  UserMode3->setPropertyV(WSNgroup,"UserMode");
  UserMode3->setPropertyV(WSNid,(short)2);
  UserMode3->setPropertyV(WSNstatus,(WSCbool)1);
  UserMode3->setPropertyV(WSNlabelString,"Mode3");
  UserMode3->setPropertyV(WSNname,"UserMode3");
  UserMode3->setPropertyV(WSNvis,(WSCbool)1);
  UserMode3->setPropertyV(WSNx,(short)15);
  UserMode3->setPropertyV(WSNy,(short)70);
  UserMode3->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode3->setPropertyV(WSNheight,(unsigned short)25);

  UserMode4 = new  WSCvradio(UerMode,"UserMode4");
      UserMode4->initialize();
  UserMode4->setPropertyV(WSNunique,(WSCbool)1);
  UserMode4->setPropertyV(WSNgroup,"UserMode");
  UserMode4->setPropertyV(WSNid,(short)3);
  UserMode4->setPropertyV(WSNlabelString,"Mode4");
  UserMode4->setPropertyV(WSNname,"UserMode4");
  UserMode4->setPropertyV(WSNvis,(WSCbool)1);
  UserMode4->setPropertyV(WSNx,(short)15);
  UserMode4->setPropertyV(WSNy,(short)95);
  UserMode4->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode4->setPropertyV(WSNheight,(unsigned short)25);

  UserMode5 = new  WSCvradio(UerMode,"UserMode5");
      UserMode5->initialize();
  UserMode5->setPropertyV(WSNunique,(WSCbool)1);
  UserMode5->setPropertyV(WSNgroup,"UserMode");
  UserMode5->setPropertyV(WSNid,(short)4);
  UserMode5->setPropertyV(WSNlabelString,"Mode5");
  UserMode5->setPropertyV(WSNname,"UserMode5");
  UserMode5->setPropertyV(WSNvis,(WSCbool)1);
  UserMode5->setPropertyV(WSNx,(short)15);
  UserMode5->setPropertyV(WSNy,(short)120);
  UserMode5->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode5->setPropertyV(WSNheight,(unsigned short)25);

  UserMode6 = new  WSCvradio(UerMode,"UserMode6");
      UserMode6->initialize();
  UserMode6->setPropertyV(WSNunique,(WSCbool)1);
  UserMode6->setPropertyV(WSNgroup,"UserMode");
  UserMode6->setPropertyV(WSNid,(short)5);
  UserMode6->setPropertyV(WSNlabelString,"Mode6");
  UserMode6->setPropertyV(WSNname,"UserMode6");
  UserMode6->setPropertyV(WSNvis,(WSCbool)1);
  UserMode6->setPropertyV(WSNx,(short)125);
  UserMode6->setPropertyV(WSNy,(short)20);
  UserMode6->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode6->setPropertyV(WSNheight,(unsigned short)25);

  UserMode11 = new  WSCvradio(UerMode,"UserMode11");
      UserMode11->initialize();
  UserMode11->setPropertyV(WSNunique,(WSCbool)1);
  UserMode11->setPropertyV(WSNgroup,"UserMode");
  UserMode11->setPropertyV(WSNid,(short)10);
  UserMode11->setPropertyV(WSNlabelString,"Mode11");
  UserMode11->setPropertyV(WSNname,"UserMode11");
  UserMode11->setPropertyV(WSNvis,(WSCbool)1);
  UserMode11->setPropertyV(WSNx,(short)235);
  UserMode11->setPropertyV(WSNy,(short)20);
  UserMode11->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode11->setPropertyV(WSNheight,(unsigned short)25);

  UserMode7 = new  WSCvradio(UerMode,"UserMode7");
      UserMode7->initialize();
  UserMode7->setPropertyV(WSNunique,(WSCbool)1);
  UserMode7->setPropertyV(WSNgroup,"UserMode");
  UserMode7->setPropertyV(WSNid,(short)6);
  UserMode7->setPropertyV(WSNlabelString,"Mode7");
  UserMode7->setPropertyV(WSNname,"UserMode7");
  UserMode7->setPropertyV(WSNvis,(WSCbool)1);
  UserMode7->setPropertyV(WSNx,(short)125);
  UserMode7->setPropertyV(WSNy,(short)45);
  UserMode7->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode7->setPropertyV(WSNheight,(unsigned short)25);

  UserMode8 = new  WSCvradio(UerMode,"UserMode8");
      UserMode8->initialize();
  UserMode8->setPropertyV(WSNunique,(WSCbool)1);
  UserMode8->setPropertyV(WSNgroup,"UserMode");
  UserMode8->setPropertyV(WSNid,(short)7);
  UserMode8->setPropertyV(WSNlabelString,"Mode8");
  UserMode8->setPropertyV(WSNname,"UserMode8");
  UserMode8->setPropertyV(WSNvis,(WSCbool)1);
  UserMode8->setPropertyV(WSNx,(short)125);
  UserMode8->setPropertyV(WSNy,(short)70);
  UserMode8->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode8->setPropertyV(WSNheight,(unsigned short)25);

  UserMode9 = new  WSCvradio(UerMode,"UserMode9");
      UserMode9->initialize();
  UserMode9->setPropertyV(WSNunique,(WSCbool)1);
  UserMode9->setPropertyV(WSNgroup,"UserMode");
  UserMode9->setPropertyV(WSNid,(short)8);
  UserMode9->setPropertyV(WSNlabelString,"Mode9");
  UserMode9->setPropertyV(WSNname,"UserMode9");
  UserMode9->setPropertyV(WSNvis,(WSCbool)1);
  UserMode9->setPropertyV(WSNx,(short)125);
  UserMode9->setPropertyV(WSNy,(short)95);
  UserMode9->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode9->setPropertyV(WSNheight,(unsigned short)25);

  UserMode10 = new  WSCvradio(UerMode,"UserMode10");
      UserMode10->initialize();
  UserMode10->setPropertyV(WSNunique,(WSCbool)1);
  UserMode10->setPropertyV(WSNgroup,"UserMode");
  UserMode10->setPropertyV(WSNid,(short)9);
  UserMode10->setPropertyV(WSNlabelString,"Mode10");
  UserMode10->setPropertyV(WSNname,"UserMode10");
  UserMode10->setPropertyV(WSNvis,(WSCbool)1);
  UserMode10->setPropertyV(WSNx,(short)125);
  UserMode10->setPropertyV(WSNy,(short)120);
  UserMode10->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode10->setPropertyV(WSNheight,(unsigned short)25);

  UserMode12 = new  WSCvradio(UerMode,"UserMode12");
      UserMode12->initialize();
  UserMode12->setPropertyV(WSNunique,(WSCbool)1);
  UserMode12->setPropertyV(WSNgroup,"UserMode");
  UserMode12->setPropertyV(WSNid,(short)11);
  UserMode12->setPropertyV(WSNlabelString,"Mode12");
  UserMode12->setPropertyV(WSNname,"UserMode12");
  UserMode12->setPropertyV(WSNvis,(WSCbool)1);
  UserMode12->setPropertyV(WSNx,(short)235);
  UserMode12->setPropertyV(WSNy,(short)45);
  UserMode12->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode12->setPropertyV(WSNheight,(unsigned short)25);

  UserMode13 = new  WSCvradio(UerMode,"UserMode13");
      UserMode13->initialize();
  UserMode13->setPropertyV(WSNunique,(WSCbool)1);
  UserMode13->setPropertyV(WSNgroup,"UserMode");
  UserMode13->setPropertyV(WSNid,(short)12);
  UserMode13->setPropertyV(WSNlabelString,"Mode13");
  UserMode13->setPropertyV(WSNname,"UserMode13");
  UserMode13->setPropertyV(WSNvis,(WSCbool)1);
  UserMode13->setPropertyV(WSNx,(short)235);
  UserMode13->setPropertyV(WSNy,(short)70);
  UserMode13->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode13->setPropertyV(WSNheight,(unsigned short)25);

  UserMode14 = new  WSCvradio(UerMode,"UserMode14");
      UserMode14->initialize();
  UserMode14->setPropertyV(WSNunique,(WSCbool)1);
  UserMode14->setPropertyV(WSNgroup,"UserMode");
  UserMode14->setPropertyV(WSNid,(short)13);
  UserMode14->setPropertyV(WSNlabelString,"Mode14");
  UserMode14->setPropertyV(WSNname,"UserMode14");
  UserMode14->setPropertyV(WSNvis,(WSCbool)1);
  UserMode14->setPropertyV(WSNx,(short)235);
  UserMode14->setPropertyV(WSNy,(short)95);
  UserMode14->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode14->setPropertyV(WSNheight,(unsigned short)25);

  UserMode15 = new  WSCvradio(UerMode,"UserMode15");
      UserMode15->initialize();
  UserMode15->setPropertyV(WSNunique,(WSCbool)1);
  UserMode15->setPropertyV(WSNgroup,"UserMode");
  UserMode15->setPropertyV(WSNid,(short)14);
  UserMode15->setPropertyV(WSNlabelString,"Mode15");
  UserMode15->setPropertyV(WSNname,"UserMode15");
  UserMode15->setPropertyV(WSNvis,(WSCbool)1);
  UserMode15->setPropertyV(WSNx,(short)235);
  UserMode15->setPropertyV(WSNy,(short)120);
  UserMode15->setPropertyV(WSNwidth,(unsigned short)80);
  UserMode15->setPropertyV(WSNheight,(unsigned short)25);

  Uer_Prop11_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop11_Lab");
      Uer_Prop11_Lab->initialize();
  Uer_Prop11_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop11_Lab->setPropertyV(WSNlabelString,"Prop11");
  Uer_Prop11_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop11_Lab->setPropertyV(WSNname,"Uer_Prop11_Lab");
  Uer_Prop11_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop11_Lab->setPropertyV(WSNx,(short)240);
  Uer_Prop11_Lab->setPropertyV(WSNy,(short)172);
  Uer_Prop11_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop6_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop6_Lab");
      Uer_Prop6_Lab->initialize();
  Uer_Prop6_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop6_Lab->setPropertyV(WSNlabelString,"Prop6");
  Uer_Prop6_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop6_Lab->setPropertyV(WSNname,"Uer_Prop6_Lab");
  Uer_Prop6_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop6_Lab->setPropertyV(WSNx,(short)125);
  Uer_Prop6_Lab->setPropertyV(WSNy,(short)172);
  Uer_Prop6_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop11 = new  WSCvifield(User_Stat_Dlg,"User_Prop11");
      User_Prop11->initialize();
  User_Prop11->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop11->setPropertyV(WSNtab,"User_Prop7");
  User_Prop11->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop11->setPropertyV(WSNshadowType,(char)1);
  User_Prop11->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop11->setPropertyV(WSNlabelString,"0");
  User_Prop11->setPropertyV(WSNname,"User_Prop11");
  User_Prop11->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop11->setPropertyV(WSNx,(short)285);
  User_Prop11->setPropertyV(WSNy,(short)172);
  User_Prop11->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop11->setPropertyV(WSNheight,(unsigned short)25);

  Uer_Prop12_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop12_Lab");
      Uer_Prop12_Lab->initialize();
  Uer_Prop12_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop12_Lab->setPropertyV(WSNlabelString,"Prop12");
  Uer_Prop12_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop12_Lab->setPropertyV(WSNname,"Uer_Prop12_Lab");
  Uer_Prop12_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop12_Lab->setPropertyV(WSNx,(short)240);
  Uer_Prop12_Lab->setPropertyV(WSNy,(short)202);
  Uer_Prop12_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop13_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop13_Lab");
      Uer_Prop13_Lab->initialize();
  Uer_Prop13_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop13_Lab->setPropertyV(WSNlabelString,"Prop13");
  Uer_Prop13_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop13_Lab->setPropertyV(WSNname,"Uer_Prop13_Lab");
  Uer_Prop13_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop13_Lab->setPropertyV(WSNx,(short)240);
  Uer_Prop13_Lab->setPropertyV(WSNy,(short)232);
  Uer_Prop13_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop14_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop14_Lab");
      Uer_Prop14_Lab->initialize();
  Uer_Prop14_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop14_Lab->setPropertyV(WSNlabelString,"Prop14");
  Uer_Prop14_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop14_Lab->setPropertyV(WSNname,"Uer_Prop14_Lab");
  Uer_Prop14_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop14_Lab->setPropertyV(WSNx,(short)240);
  Uer_Prop14_Lab->setPropertyV(WSNy,(short)262);
  Uer_Prop14_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  Uer_Prop15_Lab = new  WSCvlabel(User_Stat_Dlg,"Uer_Prop15_Lab");
      Uer_Prop15_Lab->initialize();
  Uer_Prop15_Lab->setPropertyV(WSNshadowType,(char)-1);
  Uer_Prop15_Lab->setPropertyV(WSNlabelString,"Prop15");
  Uer_Prop15_Lab->setPropertyV(WSNalignmentH,(unsigned char)0);
  Uer_Prop15_Lab->setPropertyV(WSNname,"Uer_Prop15_Lab");
  Uer_Prop15_Lab->setPropertyV(WSNvis,(WSCbool)1);
  Uer_Prop15_Lab->setPropertyV(WSNx,(short)240);
  Uer_Prop15_Lab->setPropertyV(WSNy,(short)292);
  Uer_Prop15_Lab->setPropertyV(WSNwidth,(unsigned short)50);

  User_Prop12 = new  WSCvifield(User_Stat_Dlg,"User_Prop12");
      User_Prop12->initialize();
  User_Prop12->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop12->setPropertyV(WSNtab,"User_Prop7");
  User_Prop12->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop12->setPropertyV(WSNshadowType,(char)1);
  User_Prop12->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop12->setPropertyV(WSNlabelString,"0");
  User_Prop12->setPropertyV(WSNname,"User_Prop12");
  User_Prop12->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop12->setPropertyV(WSNx,(short)285);
  User_Prop12->setPropertyV(WSNy,(short)202);
  User_Prop12->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop12->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop13 = new  WSCvifield(User_Stat_Dlg,"User_Prop13");
      User_Prop13->initialize();
  User_Prop13->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop13->setPropertyV(WSNtab,"User_Prop7");
  User_Prop13->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop13->setPropertyV(WSNshadowType,(char)1);
  User_Prop13->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop13->setPropertyV(WSNlabelString,"0");
  User_Prop13->setPropertyV(WSNname,"User_Prop13");
  User_Prop13->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop13->setPropertyV(WSNx,(short)285);
  User_Prop13->setPropertyV(WSNy,(short)232);
  User_Prop13->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop13->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop14 = new  WSCvifield(User_Stat_Dlg,"User_Prop14");
      User_Prop14->initialize();
  User_Prop14->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop14->setPropertyV(WSNtab,"User_Prop7");
  User_Prop14->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop14->setPropertyV(WSNshadowType,(char)1);
  User_Prop14->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop14->setPropertyV(WSNlabelString,"0");
  User_Prop14->setPropertyV(WSNname,"User_Prop14");
  User_Prop14->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop14->setPropertyV(WSNx,(short)285);
  User_Prop14->setPropertyV(WSNy,(short)262);
  User_Prop14->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop14->setPropertyV(WSNheight,(unsigned short)25);

  User_Prop15 = new  WSCvifield(User_Stat_Dlg,"User_Prop15");
      User_Prop15->initialize();
  User_Prop15->setPropertyV(WSNenableFep,(unsigned char)0);
  User_Prop15->setPropertyV(WSNtab,"User_Prop7");
  User_Prop15->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  User_Prop15->setPropertyV(WSNshadowType,(char)1);
  User_Prop15->setPropertyV(WSNemboss,(WSCbool)1);
  User_Prop15->setPropertyV(WSNlabelString,"0");
  User_Prop15->setPropertyV(WSNname,"User_Prop15");
  User_Prop15->setPropertyV(WSNvis,(WSCbool)1);
  User_Prop15->setPropertyV(WSNx,(short)285);
  User_Prop15->setPropertyV(WSNy,(short)292);
  User_Prop15->setPropertyV(WSNwidth,(unsigned short)60);
  User_Prop15->setPropertyV(WSNheight,(unsigned short)25);

  SweepSurf_Dlg = new  WSCdialog(Kodatuno_Win,"SweepSurf_Dlg");
      SweepSurf_Dlg->initialize();
  SweepSurf_Dlg->setPropertyV(WSNworkBackColor,"DEF1");
  SweepSurf_Dlg->setPropertyV(WSNno,(WSCbool)0);
  SweepSurf_Dlg->setPropertyV(WSNname,"SweepSurf_Dlg");
  SweepSurf_Dlg->setPropertyV(WSNtitleString,"Sweep Surface Generation");
  SweepSurf_Dlg->setPropertyV(WSNx,(short)310);
  SweepSurf_Dlg->setPropertyV(WSNy,(short)330);
  SweepSurf_Dlg->setPropertyV(WSNwidth,(unsigned short)400);
  SweepSurf_Dlg->setPropertyV(WSNheight,(unsigned short)170);
  SweepSurf_Dlg->setPropertyV(WSNtitleBar,(char)2);
    extern void SweepSurfDlg_Proc(WSCbase*);
    SweepSurf_Dlg->addProcedureV("SweepSurfDlg","SweepSurfDlg_Proc",SweepSurfDlg_Proc,2);

  DirectionOfSweep_Form = new  WSCtform(SweepSurf_Dlg,"DirectionOfSweep_Form");
      DirectionOfSweep_Form->initialize();
  DirectionOfSweep_Form->setPropertyV(WSNtitleString,"Sweep Direction Axis");
  DirectionOfSweep_Form->setPropertyV(WSNname,"DirectionOfSweep_Form");
  DirectionOfSweep_Form->setPropertyV(WSNx,(short)3);
  DirectionOfSweep_Form->setPropertyV(WSNy,(short)10);
  DirectionOfSweep_Form->setPropertyV(WSNwidth,(unsigned short)390);
  DirectionOfSweep_Form->setPropertyV(WSNheight,(unsigned short)53);
  DirectionOfSweep_Form->setPropertyV(WSNvis,(WSCbool)1);
  DirectionOfSweep_Form->setPropertyV(WSNanchorTop,(unsigned short)10);
  DirectionOfSweep_Form->setPropertyV(WSNanchorLeft,(unsigned short)3);
  DirectionOfSweep_Form->setPropertyV(WSNanchorRight,(unsigned short)7);
  DirectionOfSweep_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DirectionOfSweep_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  DirectionOfSweep_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  DOS_Label_X = new  WSCvlabel(DirectionOfSweep_Form,"DOS_Label_X");
      DOS_Label_X->initialize();
  DOS_Label_X->setPropertyV(WSNshadowType,(char)-1);
  DOS_Label_X->setPropertyV(WSNlabelString,"X");
  DOS_Label_X->setPropertyV(WSNname,"DOS_Label_X");
  DOS_Label_X->setPropertyV(WSNvis,(WSCbool)1);
  DOS_Label_X->setPropertyV(WSNx,(short)10);
  DOS_Label_X->setPropertyV(WSNy,(short)20);
  DOS_Label_X->setPropertyV(WSNwidth,(unsigned short)20);
  DOS_Label_X->setPropertyV(WSNheight,(unsigned short)20);
  DOS_Label_X->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_Label_X->setPropertyV(WSNanchorLeft,(unsigned short)10);
  DOS_Label_X->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_Label_X->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  DOS_Label_Y = new  WSCvlabel(DirectionOfSweep_Form,"DOS_Label_Y");
      DOS_Label_Y->initialize();
  DOS_Label_Y->setPropertyV(WSNshadowType,(char)-1);
  DOS_Label_Y->setPropertyV(WSNlabelString,"Y");
  DOS_Label_Y->setPropertyV(WSNname,"DOS_Label_Y");
  DOS_Label_Y->setPropertyV(WSNvis,(WSCbool)1);
  DOS_Label_Y->setPropertyV(WSNx,(short)132);
  DOS_Label_Y->setPropertyV(WSNy,(short)20);
  DOS_Label_Y->setPropertyV(WSNwidth,(unsigned short)20);
  DOS_Label_Y->setPropertyV(WSNheight,(unsigned short)20);
  DOS_Label_Y->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_Label_Y->setPropertyV(WSNanchorLeft,(unsigned short)132);
  DOS_Label_Y->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_Label_Y->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  DOS_Label_Z = new  WSCvlabel(DirectionOfSweep_Form,"DOS_Label_Z");
      DOS_Label_Z->initialize();
  DOS_Label_Z->setPropertyV(WSNshadowType,(char)-1);
  DOS_Label_Z->setPropertyV(WSNlabelString,"Z");
  DOS_Label_Z->setPropertyV(WSNname,"DOS_Label_Z");
  DOS_Label_Z->setPropertyV(WSNvis,(WSCbool)1);
  DOS_Label_Z->setPropertyV(WSNx,(short)254);
  DOS_Label_Z->setPropertyV(WSNy,(short)20);
  DOS_Label_Z->setPropertyV(WSNwidth,(unsigned short)20);
  DOS_Label_Z->setPropertyV(WSNheight,(unsigned short)20);
  DOS_Label_Z->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_Label_Z->setPropertyV(WSNanchorLeft,(unsigned short)254);
  DOS_Label_Z->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_Label_Z->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  DOS_X = new  WSCvifield(DirectionOfSweep_Form,"DOS_X");
      DOS_X->initialize();
  DOS_X->setPropertyV(WSNenableFep,(unsigned char)0);
  DOS_X->setPropertyV(WSNemboss,(WSCbool)1);
  DOS_X->setPropertyV(WSNlabelString,"0.0");
  DOS_X->setPropertyV(WSNname,"DOS_X");
  DOS_X->setPropertyV(WSNvis,(WSCbool)1);
  DOS_X->setPropertyV(WSNx,(short)30);
  DOS_X->setPropertyV(WSNy,(short)20);
  DOS_X->setPropertyV(WSNheight,(unsigned short)25);
  DOS_X->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_X->setPropertyV(WSNanchorLeft,(unsigned short)30);
  DOS_X->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_X->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  DOS_Y = new  WSCvifield(DirectionOfSweep_Form,"DOS_Y");
      DOS_Y->initialize();
  DOS_Y->setPropertyV(WSNenableFep,(unsigned char)0);
  DOS_Y->setPropertyV(WSNemboss,(WSCbool)1);
  DOS_Y->setPropertyV(WSNlabelString,"0.0");
  DOS_Y->setPropertyV(WSNname,"DOS_Y");
  DOS_Y->setPropertyV(WSNvis,(WSCbool)1);
  DOS_Y->setPropertyV(WSNx,(short)152);
  DOS_Y->setPropertyV(WSNy,(short)20);
  DOS_Y->setPropertyV(WSNheight,(unsigned short)25);
  DOS_Y->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_Y->setPropertyV(WSNanchorLeft,(unsigned short)152);
  DOS_Y->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_Y->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  DOS_Z = new  WSCvifield(DirectionOfSweep_Form,"DOS_Z");
      DOS_Z->initialize();
  DOS_Z->setPropertyV(WSNenableFep,(unsigned char)0);
  DOS_Z->setPropertyV(WSNemboss,(WSCbool)1);
  DOS_Z->setPropertyV(WSNlabelString,"1.0");
  DOS_Z->setPropertyV(WSNname,"DOS_Z");
  DOS_Z->setPropertyV(WSNvis,(WSCbool)1);
  DOS_Z->setPropertyV(WSNx,(short)274);
  DOS_Z->setPropertyV(WSNy,(short)20);
  DOS_Z->setPropertyV(WSNheight,(unsigned short)25);
  DOS_Z->setPropertyV(WSNanchorTop,(unsigned short)20);
  DOS_Z->setPropertyV(WSNanchorLeft,(unsigned short)274);
  DOS_Z->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  DOS_Z->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  SweepLen_Form = new  WSCtform(SweepSurf_Dlg,"SweepLen_Form");
      SweepLen_Form->initialize();
  SweepLen_Form->setPropertyV(WSNtitleString,"Sweep Length");
  SweepLen_Form->setPropertyV(WSNname,"SweepLen_Form");
  SweepLen_Form->setPropertyV(WSNx,(short)3);
  SweepLen_Form->setPropertyV(WSNy,(short)70);
  SweepLen_Form->setPropertyV(WSNwidth,(unsigned short)147);
  SweepLen_Form->setPropertyV(WSNheight,(unsigned short)53);
  SweepLen_Form->setPropertyV(WSNvis,(WSCbool)1);
  SweepLen_Form->setPropertyV(WSNanchorTop,(unsigned short)70);
  SweepLen_Form->setPropertyV(WSNanchorLeft,(unsigned short)3);
  SweepLen_Form->setPropertyV(WSNanchorRight,(unsigned short)250);
  SweepLen_Form->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  SweepLen_Form->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  SweepLen_Form->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  Sweep_Length = new  WSCvifield(SweepLen_Form,"Sweep_Length");
      Sweep_Length->initialize();
  Sweep_Length->setPropertyV(WSNenableFep,(unsigned char)0);
  Sweep_Length->setPropertyV(WSNemboss,(WSCbool)1);
  Sweep_Length->setPropertyV(WSNlabelString,"10");
  Sweep_Length->setPropertyV(WSNname,"Sweep_Length");
  Sweep_Length->setPropertyV(WSNvis,(WSCbool)1);
  Sweep_Length->setPropertyV(WSNx,(short)10);
  Sweep_Length->setPropertyV(WSNy,(short)20);
  Sweep_Length->setPropertyV(WSNwidth,(unsigned short)132);
  Sweep_Length->setPropertyV(WSNheight,(unsigned short)25);
  Sweep_Length->setPropertyV(WSNanchorTop,(unsigned short)20);
  Sweep_Length->setPropertyV(WSNanchorLeft,(unsigned short)10);
  Sweep_Length->setPropertyV(WSNanchorRight,(unsigned short)5);
  Sweep_Length->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  Sweep_Length->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
  Sweep_Length->setPropertyV(WSNanchorRightFlag,(WSCbool)1);

  NurbsSurface_Dlg = new  WSCdialog(Kodatuno_Win,"NurbsSurface_Dlg");
      NurbsSurface_Dlg->initialize();
  NurbsSurface_Dlg->setPropertyV(WSNworkBackColor,"DEF1");
  NurbsSurface_Dlg->setPropertyV(WSNno,(WSCbool)0);
  NurbsSurface_Dlg->setPropertyV(WSNtab,"NurbsSOpt");
  NurbsSurface_Dlg->setPropertyV(WSNbacktab,"OpenNurbsSInpFile_Btn");
  NurbsSurface_Dlg->setPropertyV(WSNname,"NurbsSurface_Dlg");
  NurbsSurface_Dlg->setPropertyV(WSNtitleString,"Nurbs Surface Generator");
  NurbsSurface_Dlg->setPropertyV(WSNx,(short)300);
  NurbsSurface_Dlg->setPropertyV(WSNy,(short)320);
  NurbsSurface_Dlg->setPropertyV(WSNwidth,(unsigned short)200);
  NurbsSurface_Dlg->setPropertyV(WSNheight,(unsigned short)237);
  NurbsSurface_Dlg->setPropertyV(WSNtitleBar,(char)2);
    extern void NurbsSDlg_Proc(WSCbase*);
    NurbsSurface_Dlg->addProcedureV("NurbsSDlg","NurbsSDlg_Proc",NurbsSDlg_Proc,2);

  NurbsSOpt = new  WSCradioGroup(NurbsSurface_Dlg,"NurbsSOpt");
      NurbsSOpt->initialize();
  NurbsSOpt->setPropertyV(WSNmenuItems,"Polygonal,Interpolated 1,Approximated,null,Control Point");
  NurbsSOpt->setPropertyV(WSNvalue,(unsigned long)5);
  NurbsSOpt->setPropertyV(WSNtitleString,"Option");
  NurbsSOpt->setPropertyV(WSNtab,"NSP_U");
  NurbsSOpt->setPropertyV(WSNbacktab,"NurbsSurface_Dlg");
  NurbsSOpt->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  NurbsSOpt->setPropertyV(WSNname,"NurbsSOpt");
  NurbsSOpt->setPropertyV(WSNx,(short)3);
  NurbsSOpt->setPropertyV(WSNy,(short)10);
  NurbsSOpt->setPropertyV(WSNwidth,(unsigned short)190);
  NurbsSOpt->setPropertyV(WSNheight,(unsigned short)150);
  NurbsSOpt->setPropertyV(WSNvis,(WSCbool)1);
  NurbsSOpt->setPropertyV(WSNanchorTop,(unsigned short)10);
  NurbsSOpt->setPropertyV(WSNanchorLeft,(unsigned short)3);
  NurbsSOpt->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  NurbsSOpt->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  OpenNurbsSInpFile_Btn = new  WSCvbtn(NurbsSurface_Dlg,"OpenNurbsSInpFile_Btn");
      OpenNurbsSInpFile_Btn->initialize();
  OpenNurbsSInpFile_Btn->setPropertyV(WSNtab,"NurbsSurface_Dlg");
  OpenNurbsSInpFile_Btn->setPropertyV(WSNbacktab,"NSR_V");
  OpenNurbsSInpFile_Btn->setPropertyV(WSNlabelString,"File");
  OpenNurbsSInpFile_Btn->setPropertyV(WSNname,"OpenNurbsSInpFile_Btn");
  OpenNurbsSInpFile_Btn->setPropertyV(WSNvis,(WSCbool)1);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNx,(short)8);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNy,(short)170);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNwidth,(unsigned short)70);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNheight,(unsigned short)25);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNanchorTop,(unsigned short)170);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNanchorLeft,(unsigned short)8);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  OpenNurbsSInpFile_Btn->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);
    extern void OpenInpFile_Proc(WSCbase*);
    OpenNurbsSInpFile_Btn->addProcedureV("OpenInpFile_Proc","OpenInpFile_Proc",OpenInpFile_Proc,2);

  NurbsS_Rank_Lb = new  WSCvlabel(NurbsSurface_Dlg,"NurbsS_Rank_Lb");
      NurbsS_Rank_Lb->initialize();
  NurbsS_Rank_Lb->setPropertyV(WSNshadowType,(char)-1);
  NurbsS_Rank_Lb->setPropertyV(WSNlabelString,"Rank");
  NurbsS_Rank_Lb->setPropertyV(WSNalignmentH,(unsigned char)1);
  NurbsS_Rank_Lb->setPropertyV(WSNname,"NurbsS_Rank_Lb");
  NurbsS_Rank_Lb->setPropertyV(WSNvis,(WSCbool)1);
  NurbsS_Rank_Lb->setPropertyV(WSNx,(short)110);
  NurbsS_Rank_Lb->setPropertyV(WSNy,(short)170);
  NurbsS_Rank_Lb->setPropertyV(WSNwidth,(unsigned short)35);
  NurbsS_Rank_Lb->setPropertyV(WSNanchorTop,(unsigned short)170);
  NurbsS_Rank_Lb->setPropertyV(WSNanchorLeft,(unsigned short)110);
  NurbsS_Rank_Lb->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  NurbsS_Rank_Lb->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

  NurbsS_Rank = new  WSCvifield(NurbsSurface_Dlg,"NurbsS_Rank");
      NurbsS_Rank->initialize();
  NurbsS_Rank->setPropertyV(WSNreturn,"NurbsSurface_Dlg");
  NurbsS_Rank->setPropertyV(WSNtab,"NSR_V");
  NurbsS_Rank->setPropertyV(WSNbacktab,"NSP_V");
  NurbsS_Rank->setPropertyV(WSNenableFocusMove,(WSCbool)1);
  NurbsS_Rank->setPropertyV(WSNshadowType,(char)2);
  NurbsS_Rank->setPropertyV(WSNemboss,(WSCbool)1);
  NurbsS_Rank->setPropertyV(WSNlabelString,"4");
  NurbsS_Rank->setPropertyV(WSNname,"NurbsS_Rank");
  NurbsS_Rank->setPropertyV(WSNvis,(WSCbool)1);
  NurbsS_Rank->setPropertyV(WSNx,(short)150);
  NurbsS_Rank->setPropertyV(WSNy,(short)170);
  NurbsS_Rank->setPropertyV(WSNwidth,(unsigned short)30);
  NurbsS_Rank->setPropertyV(WSNheight,(unsigned short)25);
  NurbsS_Rank->setPropertyV(WSNanchorTop,(unsigned short)170);
  NurbsS_Rank->setPropertyV(WSNanchorLeft,(unsigned short)150);
  NurbsS_Rank->setPropertyV(WSNanchorTopFlag,(WSCbool)1);
  NurbsS_Rank->setPropertyV(WSNanchorLeftFlag,(WSCbool)1);

   Kodatuno_Win->setVisible(True);
   return Kodatuno_Win;
}

//--- end of src ---//
